name: Dependabot auto-merge ðŸ¤–
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'oesand/pyqtexa'
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: ðŸ“Œ Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: âœ… Approve
        run: gh pr review --approve "$PR_URL"

      - name: âœ¨ Merge
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
